# Usa uma imagem oficial do Node.js como base
FROM node:20

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos de dependências para o container
COPY package*.json ./

# Instala as dependências do projeto
RUN npm install

# Copia o restante do código para o container
COPY . .

# Expõe a porta que sua aplicação usa (exemplo: 3000)
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["npm", "start"]